[truck_edge_nodes]
truck-edge-local ansible_connection=local ansible_python_interpreter=/Users/vinaychaitu/Desktop/BITSPILANI_Mtech_AI_ML_Materials/Sem-3/MLOE/assignment-1/mloe-group9-logibridge-assignment/.venv/bin/python3
